### ISSUE TITLE
feature request: database as repository

### ISSUE THREAD

**Issue by ltutar** [WianVos/puppet-xlrelease#3]
I really would like to have the database as repository support for XL Release.

**Comment by ltutar** [comment]
Also with the cluster id in order to support active / passive.

**Comment by WianVos** [comment]
This issue was moved to xebialabs/puppet-xlrelease#3

**Comment by WianVos** [comment]
levent .. could you provide a valid database config for xl-release so that i can turn that into a template
db type makes no difference
