### ISSUE TITLE
bug: puppet run will reset the password to clear text

### ISSUE THREAD

**Issue by ltutar** [WianVos/puppet-xlrelease#4]
The following puppet runs will change the password to its clear text value.
Info: Applying configuration version '1431027075'
Notice: /Stage[main]/Xlrelease::Config/Ini_setting[xlrelease.admin.password]/value: value changed '{b64}CAIxCbqlmdK93f2p1dtBQw\=\=' to 'xebia1'
Info: Class[Xlrelease::Config]: Scheduling refresh of Class[Xlrelease::Service]

**Comment by WianVos** [comment]
This issue was moved to xebialabs/puppet-xlrelease#4
