### ISSUE TITLE
Each puppet run will restart the xl release service

### ISSUE THREAD

**Issue by ltutar** [WianVos/puppet-xlrelease#5]
Each puppet run will restart the xl release service.

otice: /Stage[main]/Xlrelease::Config/Ini_setting[xlrelease.admin.password]/value: value changed '{b64}CAIxCbqlmdK93f2p1dtBQw\=\=' to 'xebia1'
Info: Class[Xlrelease::Config]: Scheduling refresh of Class[Xlrelease::Service]
Info: Class[Xlrelease::Service]: Scheduling refresh of Service[xl-release]
Notice: /Stage[main]/Xlrelease::Service/Service[xl-release]: Triggered 'refresh' from 1 events
Notice: unable to reach localhost:5516
Notice: unable to reach localhost:5516
Notice: unable to reach localhost:5516

The result of ps -ef | grep - jetty
501       5716  5707 16 21:36 ?        00:00:44 /usr/lib/jv
501       6165  6156 95 21:41 ?        00:00:11 /usr/li

**Comment by WianVos** [comment]
fixed it .. 

Created a fact to read the encrypted password .. 
ass long as there is an encrypted password in the config file .. the password will not be reset

**Comment by WianVos** [comment]
This issue was moved to xebialabs/puppet-xlrelease#5
