### ISSUE TITLE
bug: Xlrelease_xld_server tries to authenticate with a wrong parameter

### ISSUE THREAD

**Issue by ltutar** [WianVos/puppet-xlrelease#7]
I have the following yaml.
xlrelease::xlr_version: '4.6.0'
xlrelease::xlr_licsource: 'puppet:///modules/xlrelease/license/xl-release-license.lic'
xlrelease::install_type: 'puppetfiles'
xlrelease::puppetfiles_xlrelease_source: 'puppet:///modules/xlrelease/sources'
xlrelease::xlr_admin_password: 'xebia1'
xlrelease::xlr_rest_user: 'levent'
xlrelease::xlr_rest_password: 'tuttifrutti'

xlrelease::xlr_xldeploy_hash:
  'default':
    properties:
      url: "http://192.168.234.11:4516/deployit/"
      username: "admin"
      password: "xebia1"

When I run 'puppet agent -t', I get the following error. It looks like the parameter xlrelease::xlr_rest_user: 'levent' is being used to authenticate with XL Deploy.

rror: /Stage[main]/Xlrelease::Postconfig/Xlrelease_xld_server[default]: Could not evaluate: 746: unexpected token at 'cannot send request to deployit server 401/Cannot authenticate levent:<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 401 Cannot authenticate levent</title>
</head>
<body><h2>HTTP ERROR 401</h2>
<p>Problem accessing /repository/tree/Configuration/Deployit/default. Reason:
<pre>    Cannot authenticate levent</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
'
Notice: /Stage[main]/Xlrelease/Anchor[xlrelease::end]: Dependency Xlrelease_xld_server[default] has failures: true
Warning: /Stage[main]/Xlrelease/Anchor[xlrelease::end]: Skipping because of failed dependencies
Notice: Finished catalog run in 48.94 seconds
[root@puppetagent7 ~]#

**Comment by ltutar** [comment]
I looked into this.
The following needs to be correct in yaml:
xlrelease::xlr_rest_user: 'admin'
xlrelease::xlr_rest_password: 'xebia1'

I will close the issue.

**Comment by WianVos** [comment]
This issue was moved to xebialabs/puppet-xlrelease#7
